// Assignment Dissolve composite.
// t0 is SceneColor and t1 is the black/white mask generated by DissolveMask.PS.hlsl.
Texture2D<float4> gSceneTexture : register(t0);
Texture2D<float4> gMaskTexture : register(t1);
Texture2D<float4> gUnusedTertiary : register(t2);
SamplerState gClampSampler : register(s1);

cbuffer DissolveParams : register(b0)
{
    float gIntensity;       // 0
    float gTime;            // 1
    float gThreshold;       // 2
    float gEdgeWidth;       // 3
    float gNoiseScale;      // 4
    float gNoiseSpeed;      // 5
    float gEdgeColorR;      // 6
    float gEdgeColorG;      // 7
    float gEdgeColorB;      // 8
    float gBurnStrength;    // 9
    float gCenterX;         // 10
    float gCenterY;         // 11
    float gAspectRatio;     // 12
    float gDirectionBlend;  // 13
    float gSoftness;        // 14
    float gSeed;            // 15
};

struct PSInput
{
    float4 position : SV_POSITION;
    float2 uv : TEXCOORD0;
};

float4 main(PSInput input) : SV_TARGET
{
    float2 uv = saturate(input.uv);
    float4 sceneSample = gSceneTexture.Sample(gClampSampler, uv);
    float mask = gMaskTexture.Sample(gClampSampler, uv).r;

    float threshold = saturate(gThreshold);
    float softness = max(gSoftness, 0.0001f);
    float edgeWidth = max(gEdgeWidth, 0.0f);

    // mask < threshold is the dissolved region. Smoothstep replaces discard
    // because a fullscreen post target has no guaranteed image behind it.
    float keepMask = smoothstep(threshold - softness, threshold + softness, mask);

    // Detect only the retained side nearest the threshold, matching the
    // threshold-to-threshold+width edge method in the assignment material.
    float edgeStart = smoothstep(threshold, threshold + softness, mask);
    float edgeEnd = smoothstep(
        threshold + edgeWidth,
        threshold + edgeWidth + softness,
        mask);
    float edgeMask = saturate(edgeStart - edgeEnd);

    // Exact endpoints make automated transitions and demonstrations stable.
    if (threshold <= 0.0001f)
    {
        keepMask = 1.0f;
        edgeMask = 0.0f;
    }
    else if (threshold >= 0.9999f)
    {
        keepMask = 0.0f;
        edgeMask = 0.0f;
    }

    float3 dissolvedColor = float3(0.003f, 0.006f, 0.014f);
    float3 effectColor = lerp(dissolvedColor, sceneSample.rgb, keepMask);
    float3 edgeColor = max(float3(gEdgeColorR, gEdgeColorG, gEdgeColorB), 0.0f);
    effectColor += edgeColor * edgeMask * max(gBurnStrength, 0.0f);

    float3 finalColor = lerp(sceneSample.rgb, effectColor, saturate(gIntensity));
    return float4(saturate(finalColor), sceneSample.a);
}
